# Generated by Django 5.2.8 on 2025-11-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0002_alter_userprofile_address_alter_userprofile_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("admin", "Admin")],
                default="customer",
            ),
        ),
    ]
